# -*- coding: utf-8 -*-
"""Anagrama.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ChMOCp6Ay1JX43h_beyCx_SNuN6Gdc4i
"""

def anagrama(str1, str2):
  if str1.lower() == str2.lower():
    return False  # Si las palabras son idénticas, no son anagramas
  cadena1 = sorted(str1)
  cadena2 = sorted(str2)
  return cadena1 == cadena2

cadena1 = input("ingrese la primera palabra a comaparar: ")
cadena2 = input("Ingrese la segunda palabra a comparar: ")

if anagrama(cadena1, cadena2):
    print(f"'{cadena1}' y '{cadena2}' son anagramas.")
else:
    print(f"'{cadena1}' y '{cadena2}' no son anagramas.")