# -*- coding: utf-8 -*-
"""correos_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/174jScW1jG-Wx3nPoocYir2XULMZSuOEZ
"""

def fun_correo(nombre, apellido, fecha):
  nombre = nombre[:2]
  apellido = apellido[:2]
  fecha = fecha[:2]

  orden = nombre + apellido + fecha + "@gamial.com"

  return orden

nombre = input("Ingresa el nombre: ").lower()
apellido = input("Ingresa el apellido: ").lower()
fecha = input("Introduce la fecha (dd/mm/aaaa): ").lower()

correo_usuario = fun_correo(nombre, apellido, fecha)
print("Tu correo es:", correo_usuario)