# -*- coding: utf-8 -*-
"""secuencia_fibonnaci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uJcNCKl2q0APlhlMmQu7LEWlnFNsGS4n
"""

# Solicitamos la cantidad  de numeros para la secuencia que deseamos generar
num = int(input("Ingrese la cantidad de números de la secuencia que deseas generar: "))

# Verificamos que n sea un número positivo
if num <= 0:
    print("El número ingresado debe ser positivo.")
else:
    # Inicializamos los dos primeros números de la secuencia
    a = 0
    b = 1
    # Imprimimos los dos primeros números
    print(a)
    print(b)

    # Comenzamos desde el tercer número hasta el n-ésimo número
    for _ in range(2, num):
        # Calculamos el siguiente número sumando los dos anteriores
        next = a + b
        # Imprimimos el siguiente número
        print(next)
        # Actualizamos los valores de a y b para la próxima iteración
        a = b
        b = next