# -*- coding: utf-8 -*-
"""Triangulo_de_pascal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12dY7N_R--WTnRtDgC2y_MBs77IlWDW0D
"""

num = int(input("Ingrese el número de filas: "))

# Calcular el ancho total del triángulo
ancho_total = num * 2 - 1

for n in range(num):
    # Calcular la cantidad de espacios en blanco necesarios para centrar la fila
    espacios_en_blanco = (ancho_total - (n * 2 + 1)) // 2

    # Imprimir los espacios en blanco para centrar la fila
    print(" " * espacios_en_blanco, end="")

    valor = 1
    for m in range(n + 1):
        print(" ", valor, sep="", end="")
        valor = valor * (n - m) // (m + 1)

    print()